spring:
  application:
    name: Transaction-Categories-And-Interest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/transaction_categories_and_interest
    username: postgres
    password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            format_sql: true
            use_sql_comments: true
